### ISSUE TITLE
More colors

### ISSUE THREAD

**Issue by willis936** [akinomyoga/cxxmatrix#11]
The index color above 8 just resets the pattern of the indices 0 through 8.  It would be nice if the rest of the range up to 255 could be used for more colors.  Notably, an amber like in the old terminals would be nice.

https://superuser.com/questions/361297/what-colour-is-the-dark-green-on-old-fashioned-green-screen-computer-displays/1206781#1206781

**Comment by akinomyoga** [comment]
Thank you for the suggestion, but I couldn't get what you actually want. Could you explain it in detail?

> The index color above 8 just resets the pattern of the indices 0 through 8.

Hmm? Index colors are unrelated to the patterns or characters shown in the display. Am I missing something? What do you mean by *pattern*?

> It would be nice if the rest of the range up to 255 could be used for more colors.

`cxxmatrix` already uses the index colors of the range 16-255. Also, you can change the color by `-c` option. For example, you can try `cxxmatrix -c 220` or something for the amber color.

> Notably, an amber like in the old terminals would be nice.
>
> https://superuser.com/questions/361297/what-colour-is-the-dark-green-on-old-fashioned-green-screen-computer-displays/1206781#1206781

I couldn't get how the old terminal and the link are related to the 256 index colors. In these old terminals, there was no 256 index color support. Also, 256 index colors are not mentioned in the page you linked.

**Comment by willis936** [comment]
Oh I see now.  I ran through the first 16 colors and then checked 255 and thought that it was just repeating.  I didn't realize it was a standard.  214 is very close.

https://jonasjacek.github.io/colors/

**Comment by akinomyoga** [comment]
Ah, OK. Now I understood what confused you. `cxxmatrix` uses only the hue of the specified color and extends it to the eleven levels (from black to brighter colors) using 256 index colors. When it extends the color, `cxxmatrix` assumes the [VGA](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit) for the 16 color palette. The index color 8-15 are just a brighter version of the colors 0-7 in VGA, so 8-16 are just the repetition of 0-7.

Anyway thank you for the feedback trying to enhance `cxxmatrix`!
