### ISSUE TITLE
Allow setting flags of C++ compiler at runtime

### ISSUE THREAD

**Issue by matt9ucci** [akinomyoga/cxxmatrix#13]
Edit: The following original comment is not correct. We can set the flags by `make CXXFLAGS='...'`.

Original:
****
Currently not able to customise the flags defined in `GNUmakefile` without modifying them directly.

When I `make` the project for debugging, I want to add `-g` to `CXXFLAGS` and replace `-Ofast` with `-Og` like this:

```sh
make CXXFLAGS='-std=c++17 -Wall -Wextra -g -Og'
```

But `CXXFLAGS` is not affected, because it is hardcoded in [GNUmakefile](https://github.com/akinomyoga/cxxmatrix/blob/4cfd20ae860ec0bfeca0d897e03236048103dbd4/GNUmakefile#L27):

```
CXXFLAGS := -std=c++17 -Wall -Wextra -Ofast
```

It would be nice to provide a handy way to set the flags at runtime, for example,  `CXXFLAGS ?= ...` instead of `CXXFLAGS := ...`.

**Comment by akinomyoga** [comment]
Thanks! Hmm, but that's weird. The above command you suggested should work. Did you actually try that command? See [6.7 The override Directive - GNU make](https://www.gnu.org/software/make/manual/html_node/Override-Directive.html#Override-Directive). Unless `override` is specified, the user-supplied variable assignment has a higher precedence over `var := value` in `GNUmakefile`. If it doesn't work, maybe are you using an old version of GNU make? Which version of GNU make do you use?

**Comment by matt9ucci** [comment]
`make --version`: GNU Make 4.2.1 Built for x86_64-pc-linux-gnu

> The above command you suggested should work.

It works. Sorry I am an idiot. Possibly due to a typo or forgetting to reload VS Code window. (I ran the command by using VS Code tasks.json in Docker devcontainer backed WSL2, but there are some problems: e.g. https://github.com/microsoft/vscode-remote-release/issues/3497 )

I am enjoying cxxmatrix this weekend. Thank you so much.

**Comment by akinomyoga** [comment]
Oh, I see. Anyway, it's good hear that you could solve the problem! Thank you for trying `cxxmatrix`!
