### ISSUE TITLE
[feature request] sysinfo scene

### ISSUE THREAD

**Issue by FalsePhilosopher** [akinomyoga/cxxmatrix#16]
Can we get a scene where it greps system info and makes that rain?

**Comment by akinomyoga** [comment]
What kind of system information would you like to put in the scene?

**Comment by FalsePhilosopher** [comment]
@akinomyoga thanks for the response! lm-sensor outputs, cpu/disk/network usage, disk/ram used/free space, battery %, running processes, network info, version info, uptime, and anything else you could think of what you would want to see when monitoring your system but in a more fun matrix rain type of way lol.

**Comment by FalsePhilosopher** [comment]
@akinomyoga a quick c based linux sys info git search pulled this up to possibly be used as a starting point.
https://github.com/Jinjinov/Hardware.Info/blob/master/Hardware.Info/Linux/HardwareInfoRetrieval.cs

**Comment by akinomyoga** [comment]
It seems like literally everything. You seem to be requesting me to reinvent an ultimate tool that unifies top + ps + neofetch + dstat + vmstat + whatever system diagnostic tools. In addition, we need to write code for each operating system separately. Obviously, I don't have time to work on such a mostly endless project.

I doubt you really need all of these system statuses. Please specify a finite (and not so large) set of information that you actually need to show for your purpose.

> @akinomyoga a quick c based linux sys info git search pulled this up to possibly be used as a starting point.
> https://github.com/Jinjinov/Hardware.Info/blob/master/Hardware.Info/Linux/HardwareInfoRetrieval.cs

This is not C but C# which is an incompatible language and relies on completely different runtime libraries.
