### ISSUE TITLE
issues compiling on Arch

### ISSUE THREAD

**Issue by gammons** [akinomyoga/cxxmatrix#5]
Hi!  I'm trying to compile using the instructions on an up-to-date arch installation.  Here's what I'm seeing:

```
➜  cxxmatrix git:(master) make
g++ -std=c++17 -Wall -Wextra -Os -MD -MP -MF cxxmatrix.dep -c -o cxxmatrix.o cxxmatrix.cpp
In file included from cxxmatrix.cpp:595:
glyph.inl:78:2: error: converting to execution character set: Invalid argument
   78 | {U'', 21, {127, 65, 65, 65, 65, 65, 127, }},
      |  ^~~~
glyph.inl:79:2: error: converting to execution character set: Invalid argument
   79 | {U'', 21, {573695, 2072768, 104616, 104344, 37000, 1609860, 430211, }},
      |  ^~~~
glyph.inl:80:2: error: converting to execution character set: Invalid argument
   80 | {U'', 21, {164354, 260859, 2015779, 1221155, 692770, 429602, 1238014, }},
      |  ^~~~
glyph.inl:81:2: error: converting to execution character set: Invalid argument
   81 | {U'', 21, {526408, 1044472, 796815, 1841292, 659452, 592138, 583945, }},
      |  ^~~~
glyph.inl:82:2: error: converting to execution character set: Invalid argument
   82 | {U'', 21, {33, 8161, 4159, 4136, 4136, 4134, 8161, }},
      |  ^~~~
glyph.inl:83:2: error: converting to execution character set: Invalid argument
   83 | {U'', 21, {0, 0, 0, 0, 0, 0, 0, }},
```

This goes on for quite a bit, but hopefully that's enough to let me know what might be happening.  

Thanks!

**Comment by akinomyoga** [comment]
Thank you for the report! I've already added a fix for [Issue \#3](https://github.com/akinomyoga/cxxmatrix/issues/3#issuecomment-596086359) just about 20 minutes ago. I've confirmed that it successfully compiles in my Arch (5.4.8-arch1-1) in VM.

Which commit do you use? Can you try the latest commit?

**Comment by gammons** [comment]
Hi @akinomyoga my master is at https://github.com/akinomyoga/cxxmatrix/commit/385878cc4fa9b2529be779d9c412439488a5a50e.

**Comment by akinomyoga** [comment]
Thank you for the information! OK. It seems there is an issue related to the character encoding (see #3). Maybe you could also check [my comment in \#3](https://github.com/akinomyoga/cxxmatrix/issues/3#issuecomment-596089592).

**Comment by akinomyoga** [comment]
> From *#3*
>
> I changed so that Unicode characters do not appear in glyph.def. I think the problem should not occur any more. I'll close the issue. If you have still the same problem with the latest version, please reopen it. Thank you.

This problem should also be solved by the latest commit. Please try `make clean` & `make all`. Thank you
