### ISSUE TITLE
[Feature] Ability to switch between scenes

### ISSUE THREAD

**Issue by richrd** [akinomyoga/cxxmatrix#6]
Hi! Really nice project!

It'd be really handy to be able to choose to only show a specific scene(s) via a command line argument. Also switching scenes on demand with e.g. the number keys while it's running would be really nice.

**Comment by akinomyoga** [comment]
Supported. Could you please check `./cxxmatrix --help` and see if it works?

**Comment by richrd** [comment]
Wow that was really quick, many thanks! Just tested it and it works great. 
I'm sort of collecting a list of various cool terminal effects and this one is definitely going high on the list. Ever since seeing this gif I've been a bit obsessed things like this (it's stuff running in an actual terminal): https://media.giphy.com/media/fVY0d5fm6UnPG/giphy.gif

**Comment by akinomyoga** [comment]
Thank you for testing and your encouraging words!

> Ever since seeing this gif 

Maybe you already know it, but I think you will be also interested in sixel graphics which is a graphics protocol of terminals. You can find a gallery of sixel applications in the following page:
- [saitoha/libsixel: A SIXEL encoder/decoder implementation](https://github.com/saitoha/libsixel)

**Comment by richrd** [comment]
Cool, I've head of SIXEL but I haven't seen that project. Thanks for sharing!
