### ISSUE TITLE
Ability to install

### ISSUE THREAD

**Issue by ignapk** [akinomyoga/cxxmatrix#7]
Currently there is no way to install the program apart from manually copying to directory in path.
I'd like to be able to do that with simple make install
Thanks

**Comment by akinomyoga** [comment]
Thank you for the suggestion! I added `make install` dd9ab1b. Please see [README](https://github.com/akinomyoga/cxxmatrix#install) for the usage. Can you check if it works?

**Comment by ignapk** [comment]
Thanks, it's working. Closing the issue

**Comment by akinomyoga** [comment]
Thank you!
